config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/team', to: 'team#index' 
  get '/contact', to: 'contact#index'
  get '/welcome', to: 'welcome#index'
  get '/welcome/:first_name', to: 'welcome#landing_page'
  get '/gossip/:id', to: 'gossip#one_gossip', as: 'gossip/id'
  get '/author', to: 'author#list'
  get '/author/:id', to: 'author#author_page', as: 'author/id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_gossip_tags
  has_many :tags, through: :join_gossip_tags
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_gossip_tags
  has_many :potins, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :potins
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def list
    @all_user = User.all
  end
  
  def author_page
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
    @all_gossip = Gossip.all
  end

  def one_gossip
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
    @author = @user.id
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @all_gossip = Gossip.all
  end

  def landing_page
    @user = User.where(first_name:params[:first_name]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author/author_page.erb
<h1> Voici la page de <%= "#{@user.first_name} #{@user.last_name}"%></h1>
<h3>Description:</h3>
<p>"<%= @user.description %>"</p>
<p><b>Age:</b>  <%= @user.age %></p>
<p><b>City:</b> <%= @user.city.name %></p>
<p><b>E-mail:</b> <%= @user.email %></p>
<p><b>Date de création du compte:</b> <%= @user.created_at %></p>

app/views/author/list.erb
<h1> Regarde en dessous. T'as vu tout le monde qu'il y a? WOOOOW!</h1>

<h3> La liste de nos fameux auteurs de potins:<h3>
<ul class="wlc">
  <% @all_user.each do |user| %>
    <li><%= "#{user.first_name} #{user.last_name}"%></li>
  <% end %>
</ul>

app/views/contact/index.erb
ludo.barat@thp.fr

app/views/gossip/index.erb
<h1> Bienvenue l'ami.e!</h1>

<h3> Voici la liste des gossips:<h3>
<ul class="wlc">
  <% @all_gossip.each do |gossip| %>
    <li>"<%= gossip.title %>" de <%= User.find(gossip.user_id).first_name %> <%= User.find(gossip.user_id).last_name %>
  <% end %>
</ul>

app/views/gossip/one_gossip.erb
<h1>Voici la page du gossip "<%= @gossip.title%>"</h1>
<h3 class="ts">Contenu:<h1>
<p class = "gs"><%= @gossip.content %></p>
<p class="right gs">Créer le <%= @gossip.created_at %> par <%= link_to "#{@user.first_name} #{@user.last_name}",author_id_path(@author) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <%= link_to "The Gossip Project" , welcome_path, class:"navbar-brand text-white"%> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home" , welcome_path, class:"nav-link"%> 
          </li>
          <li class="nav-item">
            <%= link_to "Team" , team_path, class:"nav-link"%> 
          </li>
          <li class="nav-item">
            <%= link_to "Contact" ,contact_path, class:"nav-link"%> 
          </li>
        </ul>
        <span class="navbar-text">
          Navbar text with an inline element
        </span>
      </div>
    </nav>
    <div class="center-left">
      <%= yield %>
    </div>
  </body>
</html>

app/views/team/index.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    La team: Anaïs, Antho, Bruno, Jean, Pierre, Xavier! et bien d'autres...
  </body>
</html>

app/views/welcome/index.erb
<section class="container">

<h1> Bienvenue l'ami.e!</h1>

<h3> Voici la liste des gossips:<h3>
<ul class="wlc row">
  <% @all_gossip.each do |gossip| %>
  <div class="card border-info m-4 col-3">
    <div class="card-body">
      <h5 class="card-title mb-2"><%= link_to "#{gossip.title}", gossip_id_path(gossip.id) %></h5>
      <p class="card-text">"<%= "#{gossip.content[0...100]}..." %>"</p>
      <p class="card-link">de <%= link_to "#{User.find(gossip.user_id).first_name} #{User.find(gossip.user_id).last_name}",author_id_path(gossip.user_id) %></p>
    </div>
  </div>

  <% end %>
</ul>
</section>

app/views/welcome/landing_page.erb
<h1> Bienvenue <%= @user.first_name %> !</h1>

<h3>Ici c'est notre super site de potins, il est chouette, non ?<h3>